/**
 * Ad Events for Interstitial Callback
 */
export enum PrerollAdEvent {
  AD_BREAK_DONE = 'H5GA_EVENT_PREROLL_AD_BREAK_DONE',
}

/**
 * Ad Events for Interstitial Callback
 */
export enum InterstitialAdEvent {
  BEFORE_AD = 'H5GA_EVENT_INTERSTITIAL_BEFORE_AD',
  AFTER_AD = 'H5GA_EVENT_INTERSTITIAL_AFTER_AD',
  AD_BREAK_DONE = 'H5GA_EVENT_INTERSTITIAL_AD_BREAK_DONE',
}

/**
 * Ad Events for Rewarded Video Callback
 */
export enum RewardedVideoAdEvent {
  BEFORE_AD = 'H5GA_EVENT_REWARDED_VIDEO_BEFORE_AD',
  AFTER_AD = 'H5GA_EVENT_REWARDED_VIDEO_AFTER_AD',
  AD_BREAK_DONE = 'H5GA_EVENT_REWARDED_VIDEO_AD_BREAK_DONE',
  BEFORE_REWARD = 'H5GA_EVENT_REWARDED_VIDEO_BEFORE_REWARD',
  AD_DISMISSED = 'H5GA_EVENT_REWARDED_VIDEO_AD_DISMISSED',
  AD_VIEWED = 'H5GA_EVENT_REWARDED_VIDEO_AD_VIEWED',
}